app/views/auth.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user, LoginManager
from app.models import User, db
from app import login_manager
from app import bcrypt
from app import serializer #serializer helps you generate tokens
from app import hashlib #store token securely 
from app import datetime, timedelta
from app import jsonify
from app.models import PasswordResetToken
from app.controllers import send_reset_email

auth_bp =  Blueprint('auth', __name__)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    ''' route to handle http request for a user signup '''
    if request.method == 'POST':
        #extract values from request form data
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        print(f"Received signup data: Username={username}, Email={email}, Password={password}")  # i used this line for debugging
        #checks if user existing with same email or email
        existing_person = User.query.filter((User.username == username) | (User.email == email)).first()
        if existing_person:
            flash('username or email already exist.Please chose a different one', 'danger')
            return render_template('index.html')
        #if no username or email found hash passowrd using bcrypt library
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
        
        #create a new instance of to represent user
        new_user = User(username=username, email=email, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash('Signup success! Try login in', 'success')
        return redirect(url_for('auth.login'))
    return render_template('index.html') # GET request

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    ''' checks for http request for login route '''
    if request.method == 'POST':
        # retrieve form data
        email = request.form.get('email')
        password = request.form.get('password')
        print(f"Attempting login with email: {email}") #for debugging
        print(f"Provided password: {password}") # for debugging

        # query database for a user with specified email address filter by email and return first user found
        user = User.query.filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password): #hash passwords and compare
            login_user(user) # stores user info in a session  
            flash('Login success', 'success')
            print('Login success') #debugging line
            return redirect(url_for('user.home')) 
        else:
            flash('Invalid credentials', 'danger')
            return render_template('index.html')
    else:
        return render_template('index.html') # GET request to login route

#logout user
@auth_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    ''' function that logs out user from a session '''
    logout_user() #removes user session meaning user will need to authnticate to log in again
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.landing_page'))


@auth_bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    data = request.get_json()
    email = data.get('email')

    user = User.query.filter_by(email=email).first()
    #check if user exists
    if user:
        token = serializer.dumps(email, salt='password-reset-salt') #generate unique token
        hashed_token = hashlib.sha256(token.encode()).hexdigest() #hash the token

        #store hashed token in database with expiration time
        expiration_time = datetime.now() + timedelta(hours=1)
        reset_token = PasswordResetToken(user_id=user.id, token=hashed_token, expires_at=expiration_time)  #creates a new instance of PasswordResetToken
        db.session.add(reset_token)
        db.session.commit()

        #send email with token
        reset_link = url_for('auth.reset_password', token=token, _external=True) #generated full url with domain name included
        send_reset_email(user.email, reset_link) #function to send email to user with passowrd reset link
    return jsonify({'message': 'An email has been sent if it exist in our system'})


@auth_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    try:
        #load email from token using serializer.loads
        email = serializer.loads(token, salt='password-reset-salt', max_age=3600) #salt adds security
    except Exception as e:
        return 'The reset link is invalid or has expired', 400 #error message reason likely is token expired or is invalid
    if request.method == 'POST':
        new_password = request.form.get('password')

        confirm_password = request.form.get('confirm_password')

        #hash new_password
        hashed_password = bcrypt.generate_password_hash(new_password).decode('utf-8')

        user = User.query.filter_by(email=email).first() #retrieve user object from database
        if user:
            user.password = hashed_password #updates to new password
            db.session.commit()
            flash('Your password has been successfully updated', 'success')
            return redirect(url_for('auth.login'))
        else:
            return 'User not found', 404
    return render_template('reset_password.html', token=token)

app/views/contact.py
from flask import Blueprint, request, render_template
from app.models import User
from flask_mail import Message

#instance of blueprint class
contact_bp = Blueprint('contact', __name__) #name of bluprint and current module

@contact_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    ''' Handles http requests to contact routes
    '''
    if request.method == 'POST':
        #extract form data values
        subject = request.form['subject']
        email = request.form['email']
        message = request.form['message']

        #create an email message
        msg = Message(subject, sender=email,
                      recipients=['samuelkanyingi2016@gmail.com']) #Message class used to create an email message
        msg.body = f'Message from {email}\n\n {message}'

        try:
            mail.send(msg)
            flash('Message sent successfully!', 'success')
        except Exception as e:
            flash('Message  failed to send.Please try again later.', 'error')
            return redirect(url_for('contact'))
    return render_template('contact.html') #GET Request

app/views/deck.py
from flask import Blueprint, request, redirect, url_for, jsonify, flash, render_template
from flask_login import login_required, current_user
from app.models import Deck, Quiz, db
from datetime import datetime, timedelta


deck_bp = Blueprint('deck', __name__)

@deck_bp.route('/add_deck', methods=['POST'])
@login_required
def add_deck():
    ''' adds new deck in home.html'''
    if request.method == 'POST':
        print("Received POST request for adding a deck")
        title = request.form['title']
        print(f"Received title: {title}")
        # Create a new deck object
        new_deck = Deck(title=title, name='Default Name', quiz_count=0, user_id=current_user.id)
        db.session.add(new_deck)
        db.session.commit()
    
        flash('Deck created successfully!!!', 'success')
        return redirect(url_for('user.home'))
    else:
        return render_template('home.html')

@deck_bp.route('/edit_deck', methods=['POST'])
def edit_deck():
    ''' updates deck in home.html '''
    # Retrieve deck ID and new title from the form data
    deck_id = request.form.get('deck_id')
    new_title = request.form.get('title')

    if deck_id and new_title:
        # Query the deck from the database using the deck_id
        deck = Deck.query.get(deck_id)
        if deck:
            deck.title = new_title
            db.session.commit()
            flash('Deck updated successfully!!!!', 'success')
    return redirect(url_for('user.home'))


@deck_bp.route('/delete_deck/<int:deck_id>', methods=['POST', 'DELETE'])
def delete_deck(deck_id):
    ''' deletes deck and return json response to home.js file '''
    deck_to_delete = Deck.query.get_or_404(deck_id)
    db.session.delete(deck_to_delete)
    db.session.commit()

    return jsonify({'success': True}), 200 

@deck_bp.route('/deck/<int:deck_id>', methods=['GET'])
def deck_page(deck_id):
    ''' upon GET request it returns deck_page.html '''
    deck = Deck.query.get_or_404(deck_id) 
    quizzes = Quiz.query.filter_by(deck_id=deck_id).all()    
    return render_template('deck_page.html', deck=deck, quizzes=quizzes)

app/views/quiz.py
from flask import Blueprint, request, redirect, url_for, jsonify
from app.models import Quiz, db
from datetime import datetime, timedelta
from app.controllers import get_current_question

quiz_bp = Blueprint('quiz', __name__)

@quiz_bp.route('/add_quiz', methods=['POST'])
def add_quiz():
    ''' adds new question and answer in deck_page.html '''
    deck_id = request.form.get('deck_id')
    question = request.form.get('question')
    answer = request.form.get('answer')

    print("Received form data:", request.form)
    print("deck_id:", deck_id)
    print("question:", question)
    print("answer:", answer)

    if 'deck_id' in request.form and 'question' in request.form and 'answer' in request.form:
        deck_id = request.form['deck_id']
        question = request.form['question']
        answer = request.form['answer']
        new_quiz = Quiz(deck_id=deck_id, question=question, answer=answer)
        db.session.add(new_quiz)
        db.session.commit()
        return redirect(url_for('deck.deck_page', deck_id=deck_id))
    else:
        return "Error: missing form data"

@quiz_bp.route('/edit_quiz', methods=['POST'])
def edit_quiz():
    ''' edits a question and answer in deck_page.html'''
    # Retrieve form data
    quiz_id = request.form.get('quiz_id')
    question = request.form.get('question')
    answer = request.form.get('answer')

    if not quiz_id or not question or not answer:
        return "Error: Missing form data", 400  # Return an error if required data is missing

    # Find the quiz to be updated
    quiz = Quiz.query.get(quiz_id)
    if not quiz:
        return "Error: Quiz not found", 404  # Return an error if the quiz is not found

    # Update the quiz details
    quiz.question = question
    quiz.answer = answer

    db.session.commit()

    # Redirect to the page displaying the deck with the updated quizzes
    return redirect(url_for('deck.deck_page', deck_id=quiz.deck_id))

@quiz_bp.route('/delete_quiz/<int:quiz_id>', methods=['POST'])
def delete_quiz(quiz_id):
    ''' Post request to delete quiz in deck_page.html'''
    quiz = Quiz.query.get_or_404(quiz_id)
    db.session.delete(quiz)
    db.session.commit()
    return redirect(url_for('deck.deck_page', deck_id=quiz.deck_id))


@quiz_bp.route('/get_current_question_id', methods=['GET'])
def get_current_question_id():
    '''
    returns id of current question 
    used when by edit question modal popup in deck_page.html
    '''
    current_question = get_current_question()  # method to fetch the current question
    if current_question:
        return jsonify({'id': current_question.id})
    else:
        return jsonify({'error': 'No current question found'}), 404


@quiz_bp.route('/get_next_question', methods=['GET'])
def get_next_question():
    ''' retrieves next question '''
    global current_question_index #keeps track of current question
    print(f"Current question index: {current_question_index}") # debugging line
    # Fetch all questions, assuming they are ordered by id
    questions = Quiz.query.all()

    # Check if there are any more questions available
    if current_question_index < len(questions):
        next_question = questions[current_question_index]
        current_question_index += 1  # Move to the next question
        return jsonify({
            'question': next_question.question,
            'id': next_question.id,
            'total_questions': len(questions)
        })
    else:
        print("No more questions available")  # Debugging line

app/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact form</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/favicon_io/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon_io/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/contact.css') }}">

</head>
<style>
   
</style>
<body>
    <nav class="navbar">
        <div class="navbardiv">
            <div class="logo">
                <a href="#">FlashCard App</a>
            </div>
            <ul>
                <li><a href="{{ url_for('user.landing_page')}}">Home</a></li>
                <li><a href="{{ url_for('contact.contact') }}">Contact</a></li>                      
            </ul>
        </div>
    </nav>
    <div class="container">
    
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="flash {{ category }}"id='flash-message'>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    <h1>Contact Us</h1>
    <hr>
    <form method="post">
        <input type="text" name="subject" placeholder="Subject" required>
        <input type="email" name="email" placeholder="Your Email" required>
        <textarea name="message" placeholder="Your message" rows="5" required></textarea>
        <button type="submit">Send Message</button>

    </form>
</div>
<script>
    // show flash message
    const flashMessageElement = document.getElementById('flash-message')
    flashMessageElement.style.display = 'block';
    setTimeout(() => {
        flashMessageElement.style.display = 'none'
        window.location.href = '/'
    }, 2000);
</script>
</body>
</html>

app/templates/deck_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz page</title>
    <!-- Favicon links -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/favicon_io/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon_io/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/deck_page.css') }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.4.0/dist/confetti.browser.min.js"></script>

    <style>
 
    </style>
</head>
<body>
    <nav class="navbar">
    <div class="navbardiv">
        <div class="logo">
            <a href="#">FlashCard App</a>
        </div>
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{{ url_for('user.home') }}">Deck</a></li>
            <li><a href="{{ url_for('contact.contact') }}">Contact</a></li>            
        </ul>
    </div>
</nav>

    
<!-- <button id="addQuizBtn">Add Quiz</button> -->
 <div class="button-container">
        <button id="addQuizBtn">Add new question</button>
        <button id="takeQuizBtn">Take Quiz</button>
    </div>
<div id="table-container">
   
        <table id="quiz-table">
            <thead>
                <tr>
                    <th>Question</th>
                    <th>Answer</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="tableBody">
                {% for quiz in quizzes %}
                <tr>
                    <td class="quiz-question">{{ quiz.question }}</td>
                    <!-- <td class="quiz-answer">{{ quiz.answer }} -->
                        <td>
                        <span class="answer-text">{{ quiz.answer }}</span>
                        <span class="eye-icon" onclick=toggleAnswerVisiblity(this)>
                            <i class="fa fa-eye"></i>    
                        </span>
                    </td>
                    <td>
                    <div class="td-btn-container">
                        <!-- Edit Button -->
                        <button class="edit" data-quiz-id="{{ quiz.id }}" data-question="{{ quiz.question }}" data-answer="{{ quiz.answer }}">
                            <i class="fas fa-edit"></i>
                        </button>
                        <!-- Delete Button -->
                        <form action="{{ url_for('quiz.delete_quiz', quiz_id=quiz.id) }}" method="post"  class="inline-delete">
                            <button class="delete" type="submit">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>

<!-- Add Quiz Modal -->
<div id="addQuizModal" class="modal">
    <div class="modal-content">
        <span class="close"  id="closeAddQuizModal">&times;</span>
        <h2>Add Question & Answer</h2>
        <form id="addQuizForm" method="POST" action="{{ url_for('quiz.add_quiz', deck_id=deck.id) }}">
            <input type="hidden" name="deck_id" value="{{ deck.id }}">
            <label for="question">Question:</label> <br>
            <input type="text" id="question" name="question" required> <br>
            <label for="answer">Answer:</label> <br>
            <input type="text" id="answer" name="answer" required> <br>

            <button type="submit">Save</button>

            <button type="button" id="addMoreQuizBtn">clear</button>
        </form>
    </div>
</div>

<!-- Edit Question Modal -->
<div id="editModal" class="modal">
    <div class="modal-content">
        <span class="close" id="closeEditModal">&times;</span>
        <h2>Edit Question</h2>
        <form action="{{ url_for('quiz.edit_quiz') }}" method="post">
            <input type="hidden" id="edit-quiz-id" name="quiz_id">
            <label for="edit-question">Question:</label> <br>
            <input type="text" id="edit-question" name="question" required> <br>
            <label for="edit-answer">Answer:</label><br>
            <input type="text" id="edit-answer" name="answer" required> <br>
            <button type="submit">Save</button>
        </form>
    </div>
</div>

<!--TakeQuiz modal-->
<div id="takeQuizModal" class="modal">
    <div class = "modal-content">
        <span class= "close" id="closeTakeQuizModal">&times;</span>
        <h2>Take quiz</h2>
        <p>Quiz content goes here</p>
        <div id="feedback-container"></div>
    </div>
</div>

<!-- Delete Confirmation modal for deck_page.html -->
 <div id="deleteConfirmationModal" class="modal">
    <div class="modal-content">
        <span class="close" id="closeDeleteModal">&times;</span>
        <h2>Are you very sure you want to delete?</h2>
        <button id="confirmDeleteBtn" class="confirm-btn">Yes</button>
        <button id="cancelDeleteBtn" class="cancel-btn">No</button>
    </div>
 </div>

<!--i have inserted here to allow html to be fully loaded before loading js code-->
<script src="{{ url_for('static', filename='js/deck_page.js') }}"></script>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">

    <title>Quiz Table</title>
    <!-- Favicon links -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/favicon_io/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon_io/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
          
    <style>
    
    </style>
</head>
<nav class="navbar">
    <div class="navbardiv">
        <div class="logo">
            <a href="#">FlashCard App</a>
        </div>
        <ul>
            <li><a href="{{ url_for('user.landing_page')}}">Home</a></li>
            <li><a href="{{ url_for('contact.contact') }}">Contact</a></li>            
            
            <li><button id="logoutBtn" style="color:black; margin-right: 25px; padding: 5px 10px" onclick="{{ url_for('auth.logout') }}">Logout</a></button>

        </ul>
    </div>
</nav>

<body>
    <div id="logoutModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2> Confirm logout</h2>
            <p> Are you sure you want to logout?</p>
            <button id="confirmLogout" class="btn btn-primary">Yes</button>
            <button id="cancelLogout" class="btn btn-secondary">No</button>
        </div>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash-messages">
      {% for category, message in messages %}
        <div class="flash flash-{{ category }}">
          {{ message }}
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}

    <div id="table-container">
        {% if decks %}
        <table id="quiz-table">
            <thead>
                <tr>
                    <th>Deck</th>
                    <th>Number of quizzes </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="tableBody">
                <!-- Rows added dynamically -->
                {% for deck in decks %}
                <tr>
                <td><a href="{{ url_for('deck.deck_page', deck_id=deck.id) }}">{{ deck.title }}</a></td>
                <td>{{ deck.quiz_count }}</td>
                <td>
                
                    <button class="edit-btn" data-deck-id="{{ deck.id }}" data-deck-title="{{ deck.title }}">
                        <i class="fas fa-edit"></i>
                    </button>
                     <form id="quizForm" action="{{ url_for('deck.delete_deck', deck_id=deck.id) }}" method="post" style="display:inline;">
                        
                            <!--delete button-->
                            <button type="submit" id="delete-deck-btn" class="delete-btn" data-deck-id="{{ deck.id }}">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                     
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>You have No decks. Please add a new deck.</p>
        {% endif %}
    </div>

    <!-- Button to trigger Add popup -->            
            <button id="myBtn">Add new deck</button>
            <!--Add New Deck Modal-->
            <div id="myModal" class="modal">
                <div class="modal-content">
                    <span class="close-add-deck">&times;</span>
                    <h2> Add New Deck</h2>
                    
                    <form id="quizForm" action="/add_deck" method="post">
                        <label for="title" >Enter Deck Name:</label> <br> <br>
                        <input type="text" id="title" name="title" placeholder="deck name"> <br>
                        <button type="submit" class="save-deck-button">Save</button>
                    </form>
        
                </div>
            </div>

         <!-- Edit Modal -->
    <div id="editModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2 class="editH2">Edit Deck Name</h2>
            <form id="editForm" action="/edit_deck" method="post">
                <input type="hidden" id="edit-deck-id" name="deck_id">
                <label for="edit-deck-title">Deck Name:</label>  <br>
                <input type="text" id="edit-deck-title" name="title" required> <br>
                <button type="submit" class="edit-deck-button">Save</button>
            </form>
        </div>
    </div>


    <!-- Popup for adding a deck -->
    <div id="myPopup" class="popup">
        <div class="popup-content">
            <h2>Enter Deck Name</h2>
            <input type="text" id="deck-name-input" placeholder="Enter deck name">
            <button onclick="addDeck()">Save</button>
            <button onclick="closePopup('myPopup')">Cancel</button>
        </div>
    </div>

           <!--Confirmation Modal-->
           <div id="delete-modal" class="modal">
            <div class="modal-content">
                <p>Are you sure you want to delete the deck?</p>
                <div class="modal-actions">
                    <button id="confirm-delete-btn" class="btn btn-danger">Yes</button>
                <button id="cancel-delete-btn" class= "btn btn-secondary">No</button>
                </div>
                
            </div>
        </div>
    
    <!--i have inserted here to allow html to be fully loaded before loading js code-->
    <script src="{{ url_for('static', filename='js/home.js') }}"></script>
</body>
</html>

app/templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>landing page</title>

            <!-- Favicon links -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/favicon_io/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon_io/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
    <style>       
    </style>    
     
</head>
<body>
    <nav class="navbar">
        <div class="navbardiv">
            <div class="logo">
                <a href="#">FlashCard App</a>
            </div>
            <ul class="nav-links" id="nav-links">
                <li><a href="#">Home</a></li>
                <li><a href="{{ url_for('auth.login')}}">Decks</a></li>
                <li><a href="{{ url_for('contact.contact') }}">Contact</a></li>
                <button><a href="{{ url_for('auth.login')}}">login</a></button>
            </ul>
        </div>
    </nav>
   <div class="marquee">
    <p>"Learning never exhausts  - Leonardo da Vinci &nbsp; | &nbsp;  “The more that you read, the more things you will know.” - Dr. Seuss &nbsp;</p>
        
    </div>
    <div id="flash-message" class="flash-message">
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div class='alert-container'>
               {% for category, message in messages %}
                    <div class="alert alert-{{ category}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    </div>


    <div class="article">
        <img class="image-content" src="{{ url_for('static', filename='img/flashcard.PNG')}}" width="500" height="300"alt="quiz image">

        <h1> Welcome to my flashcard App. Your Personal learning tool</h1>
        <p>Improve your knowledge and retention on various topics <br></p>
        <p>With our quiz app you can: </p>
        <ul>
            <li> Create Custom decks for any subject or topics</li>
            <li>Add questions and answers to your decks</li>
            <li> Take quiz after adding your questions</li>
            <li>Keep track of questions you have in your decks</li>
        </ul>
        <p>Sign up now and start learning more effectively</p>
        <button class="try-now-btn"onclick="location.href='{{ url_for('auth.login')}}'">Try Now</button>
    </div>

    <script>
        const flashMessageElement = document.getElementById('flash-message')
        flashMessageElement.style.display = 'block';
            
        setTimeout(() => {
            flashMessageElement.style.display = 'none';           
            }, 2000)
        
       document.getElementById('menu-icon').addEventListener('click', function() {
        const navLinks = document.getElementById('nav-links');
        navLinks.classList.toggle('active')
       })
    </script>
</body>
</html>